apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cle1vvel9-nodejs
  janus-idp.io/tekton: cle1vvel9-nodejs
  backstage.io/kubernetes-id: cle1vvel9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cle1vvel9-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
